name: Demo app tests

on: [push]

jobs:
  build:
    env:
      SCOPE_DSN: ${{ secrets.SCOPE_DSN }}
      DB_PASS: password
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: db_user_demo_app
          POSTGRES_PASSWORD: password
          POSTGRES_DB: pythondemoapp
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Scope for Python
        uses: undefinedlabs/scope-for-python-action@v1
        with:
          dsn: ${{secrets.SCOPE_DSN}}
          command: python manage.py test
